.TH mma-mnx 1
.SH NAME
mma-mnx  \- Convert MIDI file to MMA-readable form
.SH SYNOPSIS
.PP
.B mma-mnx <somefile.mid>

.SH DESCRIPTION

This program is used to extract note and other data from an
existing midi file in a format which the MMA MidiNote command
understands.
.PP
If you just run the program on a file you will get a report as
to the number of channels in the file, etc. 
.PP
To extract data use the -c option stating the midi channel for the
data to extract. Note, Pitch Bend, Controller and Channel Aftertouch
data will be printed for the specified channel. Save using redirect
if you want. You can now use your favorite editor to import the data
to your mma file.

.SH SEE ALSO
mma(1)

.SH RESOURCES
The latest version of this program is always distributed with
.B MMA
and is available at http://www.mellowood.ca/mma

.SH AUTHOR
Bob van der Poel <bob@mellowood.ca>
.SH LICENSE
mma-mnx is Copyright 2009 Bob van der Poel. Free use of this software is granted
under the terms of the GNU General Public License.

