.TH mma-gb 1
.SH NAME
mma-gb  \- GUI browser for mma grooves
.SH SYNOPSIS
.PP
.B mma-gb

.SH DESCRIPTION

.B mma-gb
provides a simple browser for viewing grooves and their
contents.

.SH SEE ALSO
mma(1)

.SH RESCOURCES
The latest version of this program is always distributed with
.B MMA
and is available at http://www.mellowood.ca/mma

.SH AUTHOR
Bob van der Poel <bob@mellowood.ca>
.SH LICENSE
mma-gb is Copyright 2002-2008 Bob van der Poel. Free use of this software is granted
under the terms of the GNU General Public License.
