.TH synthsplit 1
.SH NAME
synthsplit  \- Create multi-track wav file from MMA file
.SH SYNOPSIS
.PP
.B synthsplit 
<somefile.mma>

.SH DESCRIPTION

.B synthsplit
creates multi-track wav file from MMA file using external synth.

.SH SEE ALSO
mma(1)

.SH RESCOURCES
The latest version of this program is always distributed with
.B MMA
and is available at http://www.mellowood.ca/mma

.SH AUTHOR
Bob van der Poel <bob@mellowood.ca>
.SH LICENSE
synthsplit is Copyright 2002-2008 Bob van der Poel. Free use of this software is granted
under the terms of the GNU General Public License.
